services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      no_cache: true
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - 51820:51820/udp # wg uses service:caddy net mode
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net
      - tunnel_net

  haproxy:
    container_name: haproxy
    build:
      context: ./haproxy
      no_cache: true
    restart: unless-stopped
    ports:
      - 222:222
    networks:
      - tunnel_net
      - proxy_net

  anubis:
    container_name: anubis
    build:
      context: ./anubis
      no_cache: true
    environment:
      BIND: ":3000"
      TARGET: http://caddy:81
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
    networks:
      - tunnel_net
      - proxy_net
 
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERS=twinkcentre
      - PERSISTENTKEEPALIVE_PEERS=all
    volumes:
      - wireguard_config:/config
    network_mode: service:caddy
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg-easy_net:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51830:51820/udp"
      - "51831:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

volumes:
  caddy_data:
  caddy_config:
  wireguard_config:
  etc_wireguard:

networks:
  proxy_net:
    name: proxy_net
  tunnel_net:
    name: tunnel_net
  wg-easy_net:
    driver: bridge
    name: wg-easy_net
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
